# Generated by Django 5.0.6 on 2024-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDetail',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.TextField()),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('sector', models.TextField()),
                ('topic', models.TextField()),
                ('insight', models.TextField()),
                ('url', models.TextField()),
                ('region', models.TextField()),
                ('impact', models.TextField()),
                ('added', models.TextField()),
                ('published', models.TextField()),
                ('country', models.TextField()),
                ('relevance', models.IntegerField()),
                ('pestle', models.TextField()),
                ('source', models.TextField()),
                ('title', models.TextField()),
                ('likelihood', models.IntegerField()),
            ],
            options={
                'db_table': 'portal_detail',
            },
        ),
    ]
