# Generated by Django 5.0.6 on 2024-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaldetail',
            name='added',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='impact',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='insight',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='pestle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='published',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='region',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='relevance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='sector',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='topic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portaldetail',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
